### ISSUE TITLE
Chiarimento motivo voto

### ISSUE THREAD

**Issue by Heldingar** [ivanarena/unipd-storia-della-tecnologia-dell-informazione#1]
Stavo cercando qualcuno che avesse pubblicato lo scritto per vedere che tipo di ricerca vuole. Ha per caso detto "cosa non andava bene" e cosa invece ha apprezzato? cioè perché da cosa ha dipeso il tuo voto.

**Comment by ivanarena** [comment]
no, nessun feedback. uno dei parametri però dovrebbe essere la partecipazione alle lezioni.

**Comment by Heldingar** [comment]
ok grazie. Sì conta la presenza anche se non si capisce bene quanto o come.

**Comment by Heldingar** [comment]
Posso chiederti quanta % di presenza avevi?

**Comment by ivanarena** [comment]
non ricordo, direi un 80%. comunque ti consiglierei di chiedere direttamente al professore.
